### ISSUE TITLE
We need to pick a type of pizza for Monday lunch. 

### ISSUE THREAD

**Issue by smanda1a382j** [IntroToCode/Spring21_Recipes_Codemates3#1]
## 💬 Discussion topic

Objective of this discussion is what type of pizzas to make for a team lunch on Monday, April 5.  We will get together and bake pizzas to celebrate being close to completion of Intro to Code.  

What toppings?

How many pizzas do we need to make?

## ❗ Potential issues

Food restrictions for teammates?
Will we be too full for dinner if we make too much? 

## People to consult

@csmith42 
@fernandomorenopayro 
@threedom 

All the members of the team.

## 📃 Details

Need to find a type of dough, a cheese(s), sauces, and cheeses!

**Comment by fernandomorenopayro** [comment]
I suggest parmesan cheese and provolone
As for toppings, I like all sorts of meats (Pepperoni, Salami, etc.) and Pesto

**Comment by fernandomorenopayro** [comment]
I have no food alergies

**Comment by threedom** [comment]
I would suggest we go for 14" pizzas and make one for each of us. 
I would suggest a purchase of 2 cans of tomatoe sauce, 2 balls of mozzarella cheese, and 1 basil plant as a baseline.
For my pizza, I'd like pepperoni sausage and olives as toppings. 
I have no food allergies.

As for time, I think making dough takes too long so maybe we buy premade dough.
Then we can probably cut and prepare things in ~15 minutes and bake the pizza for ~15 minutes each.

**Comment by csmith42** [comment]
This is a great idea, but I hate pepperoni so will need to skip pepperoni on mine.

**Comment by smanda1a382j** [comment]
We have a great pizza plan now.
