### ISSUE TITLE
We need the perfect sunday breakfast recipe.

### ISSUE THREAD

**Issue by threedom** [IntroToCode/Spring21_Recipes_Codemates3#2]
## 💬 Discussion topic

Aim of this discussion is to decide on the optimal breakfast choice for Sunday, April 4. I am planning to make breakfast for my partner and myself. She likes pancakes and eggs and I am looking for creative input on how to make them special.

## ❗ Potential issues

I might sleep too long and run out of time.
We might not have the right ingredients.
It might not taste good.

## 👥 People to consult

@csmith42  
@fernandomorenopayro 
@smanda1a382j 

## 📃 Details

In my opinion portion size should be for 3 people, because even though it is only the two of us, I eat a lot and we shouldn't run out.
I was thinking about adding fruit or something similar to the pancakes so feel free to comment what you guys think is good.
Also any other additions to make this the perfect breakfast would be great.

**Comment by smanda1a382j** [comment]
I think you should consider butter and/or whipped cream.  It's also important to choose a good type of maple syrup.

**Comment by fernandomorenopayro** [comment]
Adding chocolate chunks to pancakes are easy and tasty. 
Don't forget that pancakes need syrup... Consider that ;)

**Comment by threedom** [comment]
Hey @smanda1a382j can you suggest a good brand for maple sirup? My partner is lactose intolerant, so i will have a look at non dairy whipped cream and butter.

**Comment by smanda1a382j** [comment]
Anderson's Pure Maple Syrup is a great brand of maple syrup.

**Comment by csmith42** [comment]
Sounds like we have pancakes covered. For the eggs, we can keep it simple and do scrambled eggs. I like to add cream or milk to the eggs when mixing them together to make them nice and fluffy.

**Comment by csmith42** [comment]
We incorporated all feedback into recipe, closing issue.
