### ISSUE TITLE
We need an easy tasty dinner recipie. 

### ISSUE THREAD

**Issue by fernandomorenopayro** [IntroToCode/Spring21_Recipes_Codemates3#3]
## 💬 Discussion topic

The objective is to define and create an easy and tasty dinner recipe. This type of dinner is specific for those nights when I am tired and I just need something easy to fill that spot.

## ❗ Potential issues

-It's late at night
-There are not enough ingredients

## 👥 People to consult

@threedom 
@csmith42 
@smanda1a382j 

## 📃 Details

-Cooking should be less than 10 min
-Ingredients must be easy to find

**Comment by smanda1a382j** [comment]
Do you have a preferred kitchen appliance for making food in under 10 min?  

My suggestions: 
Something in an air fryer or microwave would be ideal for this length of time.

**Comment by threedom** [comment]
10 minutes is a tough timeline.
My suggestion:
Buy premade tomatoe soup and combine it with a quick homemade grilled cheese sandwich.
The ingredients required are one can of tomatoe soup, a loaf of bread, sliced cheese of your choice (I like Asiago), butter for the bread and for frying, maybe ham if you like fried ham and cheese sandwiches, salt and pepper to taste.

**Comment by csmith42** [comment]
I like the tomato soup and grilled cheese idea - we can also optionally add sliced tomatoes to the sandwich. if they're pre-sliced, it won't take too much time and could make it all work in 10 minutes

**Comment by threedom** [comment]
Closing this request as solution is published in [Dinner](https://github.com/IntroToCode/Spring21_Recipes_Codemates3/tree/main/dinner).
